version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/python:3.8.12
      
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!
          make clean venv test

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
